### ISSUE TITLE
AKS Kubernetes Version?

### ISSUE THREAD

**Issue by jonstelly** [virtual-kubelet/azure-aci#148]
I'm having some problems with AKS and Virtual Nodes enabled.  I'm trying to set up Knative and the knative queue sidecar injects the snippet below which generates the following output on the aci connector: `error="failed to sync pod "..." in the provider: unsupported fieldPath: status.podIP"`.

I now notice that I deployed my AKS cluster as Kubernetes 1.20.7 but the virtual node shows up as 1.18.4.  Is that the latest version of the ACI Connector?  I'm guessing I should downgrade my kubernetes deployment to a matching version?  Or is there some setting to select the version of the ACI Connector I want to use?

If my assumption is correct that this is a versioning issue, it would be nice to call out versioning requirements in the AKS Virtual Node documentation.

```
        - name: SERVING_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
```
