### ISSUE TITLE
Container instances randomly get assigned the ip "0.0.0.0"

### ISSUE THREAD

**Issue by sebastianhutter** [virtual-kubelet/azure-aci#162]
k8s version: **v1.19.13**
virtual-kubelet version: **v1.18.4-vk-azure-aci-v1.3.6**

We are experiencing an issue with the azure-ci virtual kubelet since a few days.

We have three AKS clusters running in north europe. Each of these clusters has the virtual kubelet installed via [azure cli addon command](https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli).

The virtual-kubelet integration has worked for months without problems but since a few days some container instances created via virtual-kubelet randomly get the ip "0.0.0.0" assigned instead of an ip address from the aci subnet. This happens for ~ every 5th container instance.

If we manually create container instances via the azure webinterface every single container instance receives an real ip from the aci subnet.

![image](https://user-images.githubusercontent.com/2313134/134463712-34cf33af-9e41-4c83-a266-7eeece04fcf5.png)
(container instances started via virtual-kubelet)

Here an example yaml pod manifest (used by our jenkins service to start pods in aci)
```yaml
---
apiVersion: "v1"
kind: "Pod"
metadata:
  annotations:
    buildUrl: "https://jenkins.mbp.geberit.com/job/examples/job/Execute%20jobs%20in%20ACI/110/"
    runUrl: "job/examples/job/Execute%20jobs%20in%20ACI/110/"
  labels:
    aadpodidbinding: "jenkins-agent-runner"
    jenkins: "slave"
    jenkins/label-digest: "b0fd122b7c4bc8572b842db43110f70cfe0a1023"
    jenkins/label: "examples_Execute_jobs_in_ACI_110-6srph"
  name: "examples-execute-jobs-in-aci-110-6srph-b7j8p-t5vdh"
spec:
  containers:
  - command:
    - "sleep"
    - "604800"
    image: "alpine:3"
    name: "alpine"
    resources:
      limits: {}
      requests: {}
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  - env:
    - name: "JENKINS_SECRET"
      value: "********"
    - name: "JENKINS_AGENT_NAME"
      value: "examples-execute-jobs-in-aci-110-6srph-b7j8p-t5vdh"
    - name: "JENKINS_WEB_SOCKET"
      value: "true"
    - name: "JENKINS_NAME"
      value: "examples-execute-jobs-in-aci-110-6srph-b7j8p-t5vdh"
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/home/jenkins/agent"
    - name: "JENKINS_URL"
      value: "https://jenkins.mbp.geberit.com/"
    image: "jenkins/inbound-agent:4.3-4"
    name: "jnlp"
    resources:
      limits: {}
      requests:
        memory: "256Mi"
        cpu: "100m"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  dnsPolicy: "ClusterFirst"
  imagePullSecrets:
  - name: "shared-acr"
  nodeSelector:
    kubernetes.io/role: "agent"
    beta.kubernetes.io/os: "linux"
    type: "virtual-kubelet"
  restartPolicy: "Never"
  serviceAccountName: "jenkins-agent-runner"
  tolerations:
  - key: "virtual-kubelet.io/provider"
    operator: "Exists"
  - effect: "NoSchedule"
    key: "azure.com/aci"
  volumes:
  - emptyDir:
      medium: ""
    name: "workspace-volume"
```

The virtual-kubelet logs dont show any error messages.
Here a log entry from a "failed" run - e.g. a container instance that got a "0.0.0.0" ip address

```
time="2021-09-22T19:52:13Z" level=info msg="start creating pod examples-execute-jobs-in-aci-81-x025p-ghmhh-3x9dp" addedViaRedirty=false azure.region=northeurope azure.resourceGroup=MC_iv2-shared-stg-infrastructure_iv2-shared-stg-aks_northeurope delayedViaRateLimit=5ms key=jenkins/examples-execute-jobs-in-aci-81-x025p-ghmhh-3x9dp method=aci.CreatePod name=examples-execute-jobs-in-aci-81-x025p-ghmhh-3x9dp namespace=jenkins node=virtual-node-aci-linux operatingSystem=Linux originallyAdded="2021-09-22 19:52:13.149212777 +0000 UTC m=+14042.951854502" phase=Pending plannedForWork="2021-09-22 19:52:13.154212777 +0000 UTC m=+14042.956854502" pod=examples-execute-jobs-in-aci-81-x025p-ghmhh-3x9dp provider=azure queue=syncPodsFromKubernetes reason= requeues=0 uid=3c9114c8-25fd-40e1-bb69-5768742e3353 watchedNamespace= workerId=21
time="2021-09-22T19:52:15Z" level=info msg="Created pod in provider" addedViaRedirty=false delayedViaRateLimit=5ms key=jenkins/examples-execute-jobs-in-aci-81-x025p-ghmhh-3x9dp method=createOrUpdatePod name=examples-execute-jobs-in-aci-81-x025p-ghmhh-3x9dp namespace=jenkins node=virtual-node-aci-linux operatingSystem=Linux originallyAdded="2021-09-22 19:52:13.149212777 +0000 UTC m=+14042.951854502" phase=Pending plannedForWork="2021-09-22 19:52:13.154212777 +0000 UTC m=+14042.956854502" pod=examples-execute-jobs-in-aci-81-x025p-ghmhh-3x9dp provider=azure queue=syncPodsFromKubernetes reason= requeues=0 uid=3c9114c8-25fd-40e1-bb69-5768742e3353 watchedNamespace= workerId=21
time="2021-09-22T19:52:15Z" level=info msg="Event(v1.ObjectReference{Kind:\"Pod\", Namespace:\"jenkins\", Name:\"examples-execute-jobs-in-aci-81-x025p-ghmhh-3x9dp\", UID:\"3c9114c8-25fd-40e1-bb69-5768742e3353\", APIVersion:\"v1\", ResourceVersion:\"51977872\", FieldPath:\"\"}): type: 'Normal' reason: 'ProviderCreateSuccess' Create pod in provider successfully" node=virtual-node-aci-linux operatingSystem=Linux provider=azure watchedNamespace=
```

Looking at the AzureRM activity log of the container instances there seems to be an issue with leasing the ip address.

**Operation Name** -> **Create or update Container Group** -> **Change history** -> **properties.IpAddress**
<img width="726" alt="Screenshot 2021-09-23 at 08 44 10" src="https://user-images.githubusercontent.com/2313134/134464698-57abeed4-5b4a-4515-8991-a289af75e387.png">

A successfull runs json diff - e.g. an ip address of the aci subnet is assigned - contains the following

```json
        "instanceView": {
            "events": [
                {
                    "count": 1,
                    "firstTimestamp": "2021-09-23T06:42:26Z",
                    "lastTimestamp": "2021-09-23T06:42:26Z",
                    "message": "Prepare network succeeded.",
                    "name": "PrepareNetwork",
                    "type": "Normal"
                },
                {
                    "count": 1,
                    "firstTimestamp": "2021-09-23T06:42:27Z",
                    "lastTimestamp": "2021-09-23T06:42:27Z",
                    "message": "Join network succeeded.",
                    "name": "JoinNetwork",
                    "type": "Normal"
                },
                {
                    "count": 1,
                    "firstTimestamp": "2021-09-23T06:42:27Z",
                    "lastTimestamp": "2021-09-23T06:42:27Z",
                    "message": "Delegate subnet succeeded.",
                    "name": "DelegateSubnet",
                    "type": "Normal"
                },
                {
                    "count": 1,
                    "firstTimestamp": "2021-09-23T06:42:28Z",
                    "lastTimestamp": "2021-09-23T06:42:28Z",
                    "message": "Provision network interface succeeded.",
                    "name": "ProvisionNetworkInterface",
                    "type": "Normal"
                }
            ],
            "state": "Pending"
        },
        "ipAddress": {
            "ip": "10.212.192.5",
            "ports": [],
            "type": "Private"
        },
```

An unsuccessfull runs json diff - e.g. a 0.0.0.0 ip address is assigned

```json
        "instanceView": {
            "events": [],
            "state": "Running"
        },
        "ipAddress": {
            "ip": "0.0.0.0",
            "ports": [],
            "type": "Private"
        },
```

Any ideas? We can't upgrade to the latest virtual-kubelet version (1.4.0) as we are working with the az aks addon tooling.
