### ISSUE TITLE
Unable to use AKS cluster DNS

### ISSUE THREAD

**Issue by sebastianhutter** [virtual-kubelet/azure-aci#176]
Since earlier today, maybe later afternoon yesterday, our ACI pods started via the virtual-kubelet are unable to use the cluster dns to resolve any hostname (internal or external). 

AKS version: 1.19.3
virtual-kubelet-version: 1.4.1

Here an example ACI pod manifest
```yaml
---
apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
  name: "acidnstest002"
spec:
  containers:
  - command:
    - "sleep"
    - "604800"
    image: "praqma/network-multitool"
    name: "alpine"
    tty: true
  dnsPolicy: "ClusterFirst"
  nodeSelector:
    kubernetes.io/role: "agent"
    beta.kubernetes.io/os: "linux"
    type: "virtual-kubelet"
  restartPolicy: "Never"
  tolerations:
  - key: "virtual-kubelet.io/provider"
    operator: "Exists"
  - effect: "NoSchedule"
    key: "azure.com/aci"
```

Deploying the pod creates a new ACI pod and I am able to connect to its shell via the Azure webinterface.

The pod has the following in its resolv.conf
```bash
# cat /etc/resolv.conf
nameserver 10.0.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
```

But trying to resolve any hostname times out.
```bash
# dig azure.com

; <<>> DiG 9.16.20 <<>> azure.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Using an external dns server works as expected
```bash
# dig azure.com @8.8.8.8

; <<>> DiG 9.16.20 <<>> azure.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40904
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;azure.com.                     IN      A

;; ANSWER SECTION:
azure.com.              3233    IN      A       20.37.196.198
azure.com.              3233    IN      A       20.43.132.131
azure.com.              3233    IN      A       20.49.104.40
azure.com.              3233    IN      A       20.50.2.51
azure.com.              3233    IN      A       40.112.243.51
azure.com.              3233    IN      A       40.74.100.137
azure.com.              3233    IN      A       191.235.228.36

;; Query time: 8 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Dec 07 15:23:10 UTC 2021
;; MSG SIZE  rcvd: 150
```

Connectivity between the ACI subnet and the subnets for pods is given, I can verify this by accessing a running pod directly
```bash
# curl 10.211.129.22:8080
{"timestamp":"2021-12-07T15:24:47.244+00:00","status":404,"error":"Not Found","message":"","path":"/"}
```

We see the same behaviour on three AKS clusters in three different VNets and Subscriptions. As we haven't changed anything in our setup during the last two or three weeks I expect either an API change or a change in the virtual-kubelet to be at fault. Any ideas?
