### ISSUE TITLE
initContainer not work in ACI (AKS 1.22.6 version)

### ISSUE THREAD

**Issue by zhoufenqin** [virtual-kubelet/azure-aci#229]
After creating AKS in Portal with install virtual node followed by this [doc](https://docs.microsoft.com/azure/aks/virtual-nodes-portal). The initContainer not work in ACI containers. It may caused because AKS call ACI with low apiVersion. The initContainer is supported after  2019-12-01 apiVersion in ACI

# Env
AKS version: 1.22.6
nodes in AKS cluster:
```
NAME                                STATUS   ROLES   AGE     VERSION
aks-agentpool-16213582-vmss000000   Ready    agent   5d23h   v1.22.6
aks-agentpool-16213582-vmss000002   Ready    agent   5d23h   v1.22.6
virtual-node-aci-linux              Ready    agent   5d23h   v1.19.10-vk-azure-aci-v1.4.1
```

Pods:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-helloworld-initcontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aci-helloworld
  template:
    metadata:
      labels:
        app: aci-helloworld
    spec:
      containers:
      - name: aci-helloworld
        image: mcr.microsoft.com/azuredocs/aci-helloworld
        ports:
        - containerPort: 80
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "echo initing"]
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
```

![image](https://user-images.githubusercontent.com/8765864/178918661-867b4d12-aa54-4dde-b1c1-56a2229b9994.png)
