### ISSUE TITLE
Virtual Kubelet Node is not capable of running pods throwing "DuplicateVolumes": Duplicate volumes 'kube-api-access-sndws' are found

### ISSUE THREAD

**Issue by tmcmm** [virtual-kubelet/azure-aci#303]
Since yesterday applicational pods stopped running throwing the following error:
```
Normal Scheduled 6m55s default-scheduler Successfully assigned xxxxx/test-e5ccbaf3-9xxxx5723ac2bc45-66654b7f99-f8t9c to virtual-node-aci-linux
Warning ProviderCreateFailed 75s (x16 over 6m55s) virtual-node-aci-linux/pod-controller api call to  https://management.azure.com/subscriptions/xxxxx/resourceGroups/MC_xxxxxx-aks-prod_westeurope/providers/Microsoft.ContainerInstance/containerGroups/xxxxxx?api-version=2021-07-01: got HTTP response status code 400 error code "DuplicateVolumes": Duplicate volumes 'kube-api-access-sndws' are found.
```

**Explanation:**
By default, a Pod is associated with a service account, and a credential (token) for that service account is placed into the filesystem tree of each container in that Pod, at /var/run/secrets/kubernetes.io/serviceaccount/token.
If available, a certificate bundle is placed into the filesystem tree of each container at /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, and should be used to verify the serving certificate of the API server.
Finally, the default namespace to be used for namespaced API operations is placed in a file at /var/run/secrets/kubernetes.io/serviceaccount/namespace in each container.

Tried to redeploy the application on the same namespace.
Tried to redeploy the application on a new namespace.
Tried to re-enable the virtual node addon.

From the logs of aci-connector:
kubectl logs -l app=aci-connector-linux -n kube-system
```
time="2022-09-27T12:27:43Z" level=info msg="Event(v1.ObjectReference{Kind:\"Pod\", Namespace:\"test\", Name:\"sxxxxxx9-jhq25\", UID:\"237973dd-dec6-4c86-bef6-d1cb8eb009af\", APIVersion:\"v1\", ResourceVersion:\"\", FieldPath:\"\"}): type: 'Warning' reason: '**ProviderCreateFailed**' api call to https://management.azure.com/subscriptions/xxxxxx/resourceGroup/sxxxx-prod_westeurope/providers/Microsoft.ContainerInstance/containerGroups/xxxxxx?api-version=2021-07-01: got HTTP response status code 400 error code \"DuplicateVolumes\":  Duplicate volumes 'kube-api-access-sndws' are found.." node=virtual-node-aci-linux operatingSystem=Linux provider=azure watchedNamespace=
```

Sample pod gets created and running
I have tried to create a sample pod on the same namespace and to test if it was a problem of the virtual kubelet but this new pod managed to run:

```
cat << EOF | kubectl apply -f-
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: test
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  - key: azure.com/aci
    effect: NoSchedule
  restartPolicy: Never
EOF
```
kubectl get pods -n test
NAME READY STATUS RESTARTS AGE
nginx 1/1 Running 0 79s
 

![image](https://user-images.githubusercontent.com/16254825/192557101-58978dd4-b828-411d-bdfc-6bfcd0e50b18.png)

The only thing that seems to fix is adding the following on deployment spec:
```
automountServiceAccountToken: false
```
