### ISSUE TITLE
pod stuck in Waiting state

### ISSUE THREAD

**Issue by matthew-horrocks** [virtual-kubelet/azure-aci#42]
Hi,

I'm having an issue where pods are sitting in a Waiting state for a very long time.

I opened a case with Azure support over the weekend, but wondered if it ought to be handled here also.

Here's a simple helloworld deployment and the results of a `describe pod`. Out of these 5 pods, 2 are still in a waiting state.

Possibly realted to #39 ?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-helloworld2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: aci-helloworld2
  template:
    metadata:
      labels:
        app: aci-helloworld2
    spec:
      containers:
      - name: aci-helloworld
        image: microsoft/aci-helloworld
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
```

```
matt@Azure:~/2020$ kubectl get pods -o wide; kubectl get deployments; kubectl get services; kubectl get ingress; kubectl get persistentvolumes; kubectl get nodes
NAME                               READY   STATUS    RESTARTS   AGE     IP           NODE                     NOMINATED NODE   READINESS GATES
aci-helloworld2-86b8d7866d-jg6mc   1/1     Running   0          2m49s   10.241.0.6   virtual-node-aci-linux   <none>           <none>
aci-helloworld2-86b8d7866d-kwgxc   0/1     Waiting   0          2m49s   <none>       virtual-node-aci-linux   <none>           <none>
aci-helloworld2-86b8d7866d-ndvl6   1/1     Running   0          2m49s   10.241.0.7   virtual-node-aci-linux   <none>           <none>
aci-helloworld2-86b8d7866d-xf6cj   0/1     Waiting   0          2m49s   <none>       virtual-node-aci-linux   <none>           <none>
aci-helloworld2-86b8d7866d-xl2zd   1/1     Running   0          2m49s   10.241.0.8   virtual-node-aci-linux   <none>           <none>
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
aci-helloworld2   3/5     5            3           2m49s
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.0.0.1     <none>        443/TCP   2d18h
No resources found in default namespace.
No resources found in default namespace.
NAME                                STATUS   ROLES   AGE     VERSION
aks-agentpool-11053872-vmss000000   Ready    agent   2d18h   v1.16.7
virtual-node-aci-linux              Ready    agent   2d18h   v1.14.3-vk-azure-aci-v1.2.1
```

```
matt@Azure:~/2020$ kubectl describe pod aci-helloworld2-86b8d7866d-kwgxc
Name:           aci-helloworld2-86b8d7866d-kwgxc
Namespace:      default
Priority:       0
Node:           virtual-node-aci-linux/
Labels:         app=aci-helloworld2
                pod-template-hash=86b8d7866d
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/aci-helloworld2-86b8d7866d
Containers:
  aci-helloworld:
    Container ID:   aci://628640b71d9a5123ff4a3d7bc0d8fb18bc9a262f464fc858917e02f0169a232c
    Image:          microsoft/aci-helloworld
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       Waiting
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hqrj8 (ro)
Volumes:
  default-token-hqrj8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-hqrj8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
                 kubernetes.io/role=agent
                 type=virtual-kubelet
Tolerations:     azure.com/aci:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
                 virtual-kubelet.io/provider
Events:
  Type    Reason     Age        From               Message
  ----    ------     ----       ----               -------
  Normal  Scheduled  <unknown>  default-scheduler  Successfully assigned default/aci-helloworld2-86b8d7866d-kwgxc to virtual-node-aci-linux
```
