### ISSUE TITLE
virtual-kubelet has different DNS resolution behaviour to standard kubelet 

### ISSUE THREAD

**Issue by kalioz** [virtual-kubelet/azure-aci#46]
The DNS configuration is not applied similarly between the AKS cluster and the ACI connector.

Due to the issue linked with https://github.com/virtual-kubelet/virtual-kubelet/issues/641, I added a `dnsConfig` bloc to my pods.

It worked for a while, but it is now failing to apply the dns change randomly; It didn't work at all since the start of the week.

Do you have any status on if  https://github.com/virtual-kubelet/azure-aci/pull/8 will be merged ? I could work with using a `dnsConfig` block, but I can't rely on it if it is only randomly applied.

In the ACI : 

<details><summary>CLICK ME</summary>
<p>
yaml : 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod-test-aci
spec:
  dnsConfig:
    options:
    - name: ndots
      value: "5"
    searches:
    - default.svc.cluster.local
    - svc.cluster.local
    - cluster.local
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: regcred
  containers:
  - image: ubuntu:latest
    imagePullPolicy: Always
    name: valo-back
    command: ["sleep"]
    args: ["1h"]
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources:
      requests:
        cpu: "1"
        memory: "4G"
      limits:
        cpu: "1"
        memory: "4G"
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  - key: azure.com/aci
    effect: NoSchedule
```

/etc/resolv.conf : 
```conf
nameserver 168.63.129.16
search wgomt5qrb0pevnpjyx4ypnwxvh.ax.internal.cloudapp.net
```
</p>
</details>

In the AKS: 

<details><summary>CLICK ME</summary>
<p>
yaml : 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod-test-not-aci
spec:
  dnsConfig:
    options:
    - name: ndots
      value: "5"
    searches:
    - default.svc.cluster.local
    - svc.cluster.local
    - cluster.local
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: regcred
  containers:
  - image: ubuntu:latest
    imagePullPolicy: Always
    name: valo-back
    command: ["sleep"]
    args: ["1h"]
```

/etc/resolv.conf : 
```conf
nameserver 10.3.0.10
search default.svc.cluster.local svc.cluster.local cluster.local cuftdwxpgr1e3oqz1ew1iil53e.ax.internal.cloudapp.net
options ndots:5
```
</p>
</details>

Virtual-kubelet version : 1.2.1.1

Thanks !
