### ISSUE TITLE
Projected serviceAccountToken volumn doesn't work on virtual node

### ISSUE THREAD

**Issue by karataliu** [virtual-kubelet/azure-aci#543]
**Describe the Issue**
Projected serviceAccountToken volumn  doesn't work on virtual node

**Steps To Reproduce**
kubectl apply below:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa0
---
apiVersion: v1
kind: Pod
metadata:
  name: pod0-vk
spec:
  automountServiceAccountToken: false
  containers:
  - image: nginx
    name: test
    volumeMounts:
    - mountPath: /var/run/secrets/azure/tokens
      name: azure-identity-token
      readOnly: true
  nodeSelector:
    type: virtual-kubelet
  serviceAccountName: sa0
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  volumes:
  - name: azure-identity-token
    projected:
      sources:
      - serviceAccountToken:
          path: azure-identity-token
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  automountServiceAccountToken: false
  containers:
  - image: nginx
    name: test
    volumeMounts:
    - mountPath: /var/run/secrets/azure/tokens
      name: azure-identity-token
      readOnly: true
  serviceAccountName: sa0
  volumes:
  - name: azure-identity-token
    projected:
      sources:
      - serviceAccountToken:
          path: azure-identity-token
```

Outcome:
```
NAME      READY   STATUS           RESTARTS   AGE   IP            NODE                                NOMINATED NODE   READINESS GATES
pod0-vk   0/1     ProviderFailed   0          11m   <none>        virtual-node-aci-linux              <none>           <none>
pod1      1/1     Running          0          11m   10.241.0.24   aks-nodepool1-some-vmss000000   <none>           <none>
```

Describe output:
```
Warning  ProviderCreateFailed  25s (x17 over 11m)  virtual-node-aci-linux/pod-controller  containerinstance.ContainerGroupsClient#CreateOrUpdateSender: Failure sending request: StatusCode=400 -- Original Error: Code="VolumesNotFound" Message="Volumes 'azure-identity-token' in container 'test'are not found."
```

aci connector pod log:
```
time="2023-05-05T07:12:49Z" level=info msg="Found projected volume" addedViaRedirty=false azure.region=westcentralus azure.resourceGroup=MC_doliu0505_e0_westcentralus delayedViaRateLimit=5m27.68s key=w3/pod0-vk method=aci.CreatePod name=pod0-vk namespace=w3 node=virtual-node-aci-linux operatingSystem=Linux originallyAdded="2023-05-05 07:01:43.653084411 +0000 UTC m=+12195.723507899" phase=Pending plannedForWork="2023-05-05 07:12:49.533363142 +0000 UTC m=+12861.603786652" pod=pod0-vk provider=azure queue=syncPodsFromKubernetes reason=ProviderFailed requeues=16 uid=1de63174-afd2-48b9-999c-c929f4629740 watchedNamespace= workerId=37
time="2023-05-05T07:12:49Z" level=info msg="start creating pod pod0-vk" addedViaRedirty=false azure.region=westcentralus azure.resourceGroup=MC_doliu0505_e0_westcentralus delayedViaRateLimit=5m27.68s key=w3/pod0-vk method=aci.CreatePod name=pod0-vk namespace=w3 node=virtual-node-aci-linux operatingSystem=Linux originallyAdded="2023-05-05 07:01:43.653084411 +0000 UTC m=+12195.723507899" phase=Pending plannedForWork="2023-05-05 07:12:49.533363142 +0000 UTC m=+12861.603786652" pod=pod0-vk provider=azure queue=syncPodsFromKubernetes reason=ProviderFailed requeues=16 uid=1de63174-afd2-48b9-999c-c929f4629740 watchedNamespace= workerId=37
time="2023-05-05T07:12:49Z" level=info msg="creating container group with name: w3-pod0-vk" addedViaRedirty=false azure.region=westcentralus azure.resourceGroup=MC_doliu0505_e0_westcentralus delayedViaRateLimit=5m27.68s key=w3/pod0-vk method=CreateContainerGroup name=pod0-vk namespace=w3 node=virtual-node-aci-linux operatingSystem=Linux originallyAdded="2023-05-05 07:01:43.653084411 +0000 UTC m=+12195.723507899" phase=Pending plannedForWork="2023-05-05 07:12:49.533363142 +0000 UTC m=+12861.603786652" pod=pod0-vk provider=azure queue=syncPodsFromKubernetes reason=ProviderFailed requeues=16 uid=1de63174-afd2-48b9-999c-c929f4629740 watchedNamespace= workerId=37
time="2023-05-05T07:12:50Z" level=info msg="CreateCG status code: Failed" addedViaRedirty=false azure.region=westcentralus azure.resourceGroup=MC_doliu0505_e0_westcentralus delayedViaRateLimit=5m27.68s key=w3/pod0-vk method=CreateCG name=pod0-vk namespace=w3 node=virtual-node-aci-linux operatingSystem=Linux originallyAdded="2023-05-05 07:01:43.653084411 +0000 UTC m=+12195.723507899" phase=Pending plannedForWork="2023-05-05 07:12:49.533363142 +0000 UTC m=+12861.603786652" pod=pod0-vk provider=azure queue=syncPodsFromKubernetes reason=ProviderFailed requeues=16 uid=1de63174-afd2-48b9-999c-c929f4629740 watchedNamespace= workerId=37
time="2023-05-05T07:12:50Z" level=info msg="Updated k8s pod status" addedViaRedirty=false delayedViaRateLimit=5m27.68s key=w3/pod0-vk method=createOrUpdatePod name=pod0-vk namespace=w3 node=virtual-node-aci-linux operatingSystem=Linux originallyAdded="2023-05-05 07:01:43.653084411 +0000 UTC m=+12195.723507899" phase=Pending plannedForWork="2023-05-05 07:12:49.533363142 +0000 UTC m=+12861.603786652" pod=pod0-vk podPhase=Pending provider=azure queue=syncPodsFromKubernetes reason=ProviderFailed requeues=16 uid=1de63174-afd2-48b9-999c-c929f4629740 watchedNamespace= workerId=37
time="2023-05-05T07:12:50Z" level=warning msg="requeuing \"w3/pod0-vk\" due to failed sync" addedViaRedirty=false delayedViaRateLimit=5m27.68s error="failed to sync pod \"w3/pod0-vk\" in the provider: containerinstance.ContainerGroupsClient#CreateOrUpdateSender: Failure sending request: StatusCode=400 -- Original Error: Code=\"VolumesNotFound\" Message=\"Volumes 'azure-identity-token' in container 'test'are not found.\"" key=w3/pod0-vk method=handleQueueItemObject node=virtual-node-aci-linux operatingSystem=Linux originallyAdded="2023-05-05 07:01:43.653084411 +0000 UTC m=+12195.723507899" plannedForWork="2023-05-05 07:12:49.533363142 +0000 UTC m=+12861.603786652" provider=azure queue=syncPodsFromKubernetes requeues=16 watchedNamespace= workerId=37
time="2023-05-05T07:12:50Z" level=info msg="Event(v1.ObjectReference{Kind:\"Pod\", Namespace:\"w3\", Name:\"pod0-vk\", UID:\"1de63174-afd2-48b9-999c-c929f4629740\", APIVersion:\"v1\", ResourceVersion:\"\", FieldPath:\"\"}): type: 'Warning' reason: 'ProviderCreateFailed' containerinstance.ContainerGroupsClient#CreateOrUpdateSender: Failure sending request: StatusCode=400 -- Original Error: Code=\"VolumesNotFound\" Message=\"Volumes 'azure-identity-token' in container 'test'are not found.\"" node=virtual-node-aci-linux operatingSystem=Linux provider=azure watchedNamespace=
```

**Expected behavior**
pod0-vk working well as pod1

**Virtual-kubelet version**
virtual-node-aci-linux              Ready    agent   4h36m   v1.19.10-vk-azure-aci-1.4.8

**Kubernetes version**
1.25.6

**Additional context**
