### ISSUE TITLE
Is it possible to create ACI with custom resources?

### ISSUE THREAD

**Issue by uveta** [virtual-kubelet/azure-aci#55]
I am trying to create deployment with following resource requirements and limits:

```
resources:
  requests:
    memory: "8Gi"
    cpu: "2.0"
  limits:
    memory: "8Gi"
    cpu: "2.0"
````

However, no matter which values i supply for cpu and memory, ACI with default values is created, i.e. 1 CPU core and 1.5GB memory. 

Is there a way to configure VK to supply different values to Container Group create request? The application I am trying to deploy is not able to run only with 1.5 GB of memory, hence I am trying to find a way to increase the resource value requested.
