### ISSUE TITLE
defaultMode on configmap not set

### ISSUE THREAD

**Issue by khauser** [virtual-kubelet/azure-aci#607]
**Describe the Issue**
```
  volumes:
  - configMap:
      defaultMode: 511
      name: icm-11-azure-test-icm-as-jgroups-config-xml
    name: jgroups-config-volume
```
results in a `ls -la` on a normal pod:
```
-rwxrwxrwx 1 root      intershop 2201 Apr 29 13:34 jgroups-config.xml
```
and on a virtual-kublet it's:
```
drwxr-xr-x 2 root      root      4096 Apr 29 13:34 jgroups-config.xml
```

On both I configured:
```
  securityContext:
    fsGroup: 150
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 150
    runAsNonRoot: false
    runAsUser: 150
```

**Expected behavior**
Both should look like: 
```
-rwxrwxrwx 1 root      intershop 2201 Apr 29 13:34 jgroups-config.xml
```

**Virtual-kubelet version**
`kubeletVersion: v1.25.0-vk-azure-aci-1.6.1`
**Kubernetes version**
`1.28.3`
**Additional context**
