### ISSUE TITLE
How could I deploy Windows containers on VK 1.3.1?

### ISSUE THREAD

**Issue by eugen-nw** [virtual-kubelet/azure-aci#93]
I followed the setup steps present in https://github.com/virtual-kubelet/azure-aci/blob/master/README.md#deployment-of-the-aci-provider-in-your-cluster  I use an AKS cluster.

Below is the deployment script I used so far to install on 1.2.1.  The node name at the time was ```virtual-kubelet-aci-connector-for-windows```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: boldiq-external-solver-runner-nj-test
  name: boldiq-external-solver-runner-nj-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boldiq-external-solver-runner-nj-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: boldiq-external-solver-runner-nj-test
    spec:
      containers:
      - image: externalsolverrunnersnetjets.azurecr.io/boldiq-external-solver-runner:20201103.1
        imagePullPolicy: Always
        name: boldiq-external-solver-runner-nj-test
        resources:
          requests:
            memory: 12G
            cpu: 1
      imagePullSecrets:
        - name: docker-registry-secret
      nodeName: virtual-kubelet
```
The script still runs fine, but the Pod won't start. ```kubectl decribe pod``` lists the error below which makes me believe that ACI is looking for a Linux container in ACR.
```
api call to https://management.azure.com/subscriptions/f9467991-49d6-4eb7-8df7-8d4b21e78968/resourceGroups/MC_netjets-test-scaleout_aks-netjets-test_eastus/providers/Microsoft.ContainerInstance/containerGroups/default-boldiq-external-solver-runner-nj-test-5cd5c995dd-2jk2c?api-version=2018-10-01: got HTTP response status code 400 error code "ImageOsTypeNotMatchContainerGroup": The container image 'externalsolverrunnersnetjets.azurecr.io/boldiq-external-solver-runner:20201103.1' doesn't support specified OS 'Linux' for container group 'default-boldiq-external-solver-runner-nj-test-5cd5c995dd-2jk2c'.
```
I did a bit of search and for Pod deployments I found the section below, only that the deployment no longer works as it complains that it has no knowledge of the nodeSelector and tolerations fields.
```
    nodeSelector:
      kubernetes.io/role: agent
      beta.kubernetes.io/os: windows
      type: virtual-kubelet
    tolerations:
    - key: virtual-kubelet.io/provider
      operator: Exists
    - key: azure.com/aci
      effect: NoSchedule
```

**Comment by eugen-nw** [comment]
I experimented a bit more with this and I tried to deploy the Windows container as a pod.  The script is below.  That deployment completes successfully.
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: boldiq-external-solver-runner-nj-test
  name: boldiq-external-solver-runner-nj-test
spec:
  containers:
  - image: externalsolverrunnersnetjets.azurecr.io/boldiq-external-solver-runner:20201103.1
    imagePullPolicy: Always
    name: boldiq-external-solver-runner-nj-test
    resources:
      requests:
        memory: 12G
        cpu: 1
  imagePullSecrets:
    - name: docker-registry-secret
  nodeName: virtual-kubelet
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: windows
    type: virtual-kubelet
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  - key: azure.com/aci
    effect: NoSchedule
```
The container still does not start, with the same error:
```
api call to https://management.azure.com/subscriptions/f9467991-49d6-4eb7-8df7-8d4b21e78968/resourceGroups/MC_netjets-test-scaleout_aks-netjets-test_eastus/providers/Microsoft.ContainerInstance/containerGroups/default-boldiq-external-solver-runner-nj-test?api-version=2018-10-01: got HTTP response status code 400 error code "ImageOsTypeNotMatchContainerGroup": The container image 'externalsolverrunnersnetjets.azurecr.io/boldiq-external-solver-runner:20201103.1' doesn't support specified OS 'Linux' for container group 'default-boldiq-external-solver-runner-nj-test'.
```
This makes me believe that virtual-kubelet cannot run Windows containers.  Is there any VK that can run Windows containers in ACI please?
