### ISSUE TITLE
kubectl logs doesnot give logs for azure container instances

### ISSUE THREAD

**Issue by swapnika436** [virtual-kubelet/azure-aci#98]
---

### Environment summary

Provider (Azure Container Instances)

Version (e.g. 0.1, 0.2-beta)

K8s Master Info (AKS)

Install Method (e.g. Helm Chart, )

### Repo Steps

kubectl logs <<pod name>>  and  logs = v1.read_namespaced_pod_log(<<pod name>> ,<<namespace>>)
doesnot give any logs. 

[pod_template.txt](https://github.com/virtual-kubelet/virtual-kubelet/files/5504876/pod_template.txt)

**Comment by cpuguy83** [comment]
Transferred this over from vk/vk repo.

Can you paste your template into a code block? Otherwise people have to download the text file.

**Comment by cpuguy83** [comment]
Nevermind, I just curl'd it:

```
kind: Pod
apiVersion: v1
metadata:
  labels:
    app: dask
    dask.org/cluster-name: dask-root-6b6aa531-8
    dask.org/component: scheduler
    user: root
spec:
  containers:
    - name: dask-worker
      image: daskdev/dask
      command:
        - /bin/sh
        - '-c'
      args:
        - dask-scheduler
      resources:
        limits:
          cpu: '1'
          memory: 2G
        requests:
          cpu: '1'
          memory: 2G     
      imagePullPolicy: IfNotPresent
  restartPolicy: Never 
  dnsPolicy: ClusterFirst
  nodeSelector:
    beta.kubernetes.io/os: linux
    kubernetes.io/role: agent
    type: virtual-kubelet
  serviceAccountName: default
  serviceAccount: default
  securityContext: {}
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: k8s.dask.org/node-purpose
                operator: In
                values:
                  - scheduler
  schedulerName: default-scheduler
  tolerations:
    - key: virtual-kubelet.io/provider
      operator: Exists
    - key: azure.com/aci
      effect: NoSchedule
    - key: k8s.dask.org/dedicated
      operator: Equal
      value: scheduler
      effect: NoSchedule
    - key: k8s.dask.org_dedicated
      operator: Equal
      value: scheduler
      effect: NoSchedule
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
```
